### ISSUE TITLE
README에 있는 저장소 주소를 접근할 수 없습니다

### ISSUE THREAD

**Issue by jeongm-in** [MoonHyuk/network-monitoring#1]
README에 있는 GitLab 주소로 클론을 하려 하면 `repository does not exist` 에러가 뜹니다.
현재 GitHub 저장소 주소로는 클론이 제대로 됩니다.

**Comment by MoonHyuk** [comment]
사내 private 리포지토리 경로를 적어놨었네요..
수정하였습니다. 알려주셔서 감사힙니다. 👍
